version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - sam build --template-file template.yaml
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-oww4c3mqhsxf --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml