version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
phases:
  pre_build:
    install:
     runtime-versions:
      dotnet: 3.1
    commands:
      - echo Restore started on `date`      
      - cd src
      - cd LambdaAPIInvoker
      - cd LambdaAPIInvoker
      - dotnet clean
      - dotnet restore  
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release
      - cd ..
      - cd ..
      - cd ..
      - aws cloudformation package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-oww4c3mqhsxf --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml