version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - export PATH="$PATH:/root/.dotnet/tools"
      - pip install --upgrade awscli
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-oww4c3mqhsxf --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml